### PR TITLE
Changed os and data disk defaults to Premium SSD

### PR DESCRIPTION
**Pull request by garvct**
Changed the default OS and data disk to Premium SSD's so there are no performance surprises when an NFS server or OS disk is created with default settings.

### CODE REVIEW

**Comment by garvct** [comment]
I think Premium_SSD's will typically deliver better performance than Standard SSD's. For Production environments/benchmarking I think Premium SSD's would be preferred.
If we leave Standard SSD's as the default at minimum I would like to see it as a mandatory option in the config file, so its clear that Standard SSD's are used and not Premium SSD's.

**Comment by garvct** [comment]
re-opened.

**Comment by edwardsp** [comment]
Shall we discuss and decide as a group on this one next team meeting?

**Comment by garvct** [comment]
My preference would be to create a separate PR updating config files explicitly including the disk type parameter. Would that be ok?

**Comment by xpillons** [comment]
> My preference would be to create a separate PR updating config files explicitly including the disk type parameter. Would that be ok?

Sure

**Pull request merged**
