### PR TITLE
added SLURM GRES scheduling support

### PR DESCRIPTION
**Pull request by vgamayunov**

### CODE REVIEW

**Comment by garvct** [comment]
I do not think slurm+gres is working correctly.

[hpcadmin@headnode ~]$ salloc -N 1 --gpus-per-node=8
salloc: Granted job allocation 5
[hpcadmin@compute000002 ~]$

I would expect that a node should be allocated, but not login to one.

[hpcadmin@headnode ~]$ srun -N 1 --gpus-per-node=4 --pty bash
[hpcadmin@compute000002 ~]$ nvidia-smi
Sat Sep 25 01:47:13 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      Off  | 00000001:00:00.0 Off |                    0 |
| N/A   42C    P0    62W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  A100-SXM4-40GB      Off  | 00000002:00:00.0 Off |                    0 |
| N/A   41C    P0    55W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  A100-SXM4-40GB      Off  | 00000003:00:00.0 Off |                    0 |
| N/A   42C    P0    56W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  A100-SXM4-40GB      Off  | 00000004:00:00.0 Off |                    0 |
| N/A   41C    P0    61W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  A100-SXM4-40GB      Off  | 0000000B:00:00.0 Off |                    0 |
| N/A   41C    P0    61W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  A100-SXM4-40GB      Off  | 0000000C:00:00.0 Off |                    0 |
| N/A   40C    P0    56W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  A100-SXM4-40GB      Off  | 0000000D:00:00.0 Off |                    0 |
| N/A   40C    P0    55W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  A100-SXM4-40GB      Off  | 0000000E:00:00.0 Off |                    0 |
| N/A   41C    P0    57W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

I see 8 GPU's but I should only see 4?

**Review by garvct — CHANGES_REQUESTED** [review]
Please see my comments on slurm+gres functionality.

**Comment by vgamayunov** [comment]
> [hpcadmin@headnode ~]$ salloc -N 1 --gpus-per-node=8 salloc: Granted job allocation 5 [hpcadmin@compute000002 ~]$
> 
> I would expect that a node should be allocated, but not login to one.

This is slurm.conf setting. I usually prefer it this way because you can have interactive session on GPU with all SLURM environment with salloc. Do you think it is better to stay on login after salloc?

> [hpcadmin@headnode ~]$ srun -N 1 --gpus-per-node=4 --pty bash [hpcadmin@compute000002 ~]$ nvidia-smi Sat Sep 25 > I see 8 GPU's but I should only see 4?

Fixed. This was turned off too, since SLURM sets CUDA_VISIBLE_DEVICES. I agree it would make more sense to restrict job to allocated GPUs. Now this is turned on.

**Comment by vgamayunov** [comment]
Tested like this:
```
[hpcuser@headnode ~]$ srun --gpus-per-node=2 --container-image='nvcr.io#nvidia/pytorch:21.07-py3' --container-mount
-home --pty bash
pyxis: importing docker image ...
root@compute000000:/workspace# nvidia-smi -L
GPU 0: Tesla V100-SXM2-32GB (UUID: GPU-f99b470b-763f-a830-53fa-6afd5076789b)
GPU 1: Tesla V100-SXM2-32GB (UUID: GPU-1ecd009f-aaf6-29d4-e7a3-076c717e2bbd)

[hpcuser@headnode ~]$ salloc -N1 --gpus-per-node=1
salloc: Granted job allocation 6
salloc: Waiting for resource configuration
nvidia-salloc: Nodes compute000000 are ready for job
nvidia-smi[hpcuser@compute000000 ~]$ nvidia-smi -L
GPU 0: Tesla V100-SXM2-32GB (UUID: GPU-f99b470b-763f-a830-53fa-6afd5076789b)
[hpcuser@compute000000 ~]$
[hpcuser@compute000000 ~]$ exit
salloc: Relinquishing job allocation 6
[hpcuser@headnode ~]$ salloc -N1 --gpus-per-node=4
salloc: Granted job allocation 7
salloc: Waiting for resource configuration
salloc: Nodes compute000000 are ready for job
[hpcuser@compute000000 ~]$ nvidia-smi -L
GPU 0: Tesla V100-SXM2-32GB (UUID: GPU-f99b470b-763f-a830-53fa-6afd5076789b)
GPU 1: Tesla V100-SXM2-32GB (UUID: GPU-1ecd009f-aaf6-29d4-e7a3-076c717e2bbd)
GPU 2: Tesla V100-SXM2-32GB (UUID: GPU-21c51051-0720-148c-bf43-77aef3266af6)
GPU 3: Tesla V100-SXM2-32GB (UUID: GPU-edf9d5be-6a17-7118-1326-c8b0c483fcfd)
[hpcuser@compute000000 ~]$
```

**Review by garvct — APPROVED** [review]
I would suggest changing the default salloc behavior to staying on the headnode (Same as CycleCloud+SLURM and Nephele+SLURM).
Other changes look good.

**Pull request merged**
