### PR TITLE
This is a working version of glusterfs with Cycle Cloud

### PR DESCRIPTION
**Pull request by chadnar2**
The copy of glusterfs_pool.sh inside of azurehpc was not used as it would not function with what had to be done. 
Others can see if they can get this to work.
A copy of glusterfs_pool.sh along with glusterfs_pool_master.sh has been included here. Everything was tested out.

### CODE REVIEW

**Comment by garvct** [comment]
Did these changes impact examples/glusterfs_ephemeral and examples/glusterfs_data_disks? Do they still work?

**Comment by garvct** [comment]
We need one common set of scripts for all glusterfs examples?

**Comment by chadnar2** [comment]
No changes to examples/glusterfs_ephemeral and examples/glusterfs_data_disks.

**Comment by garvct** [comment]
You have a scripts dir in cc_glusterfs? all glusterfs examples need to use the glusterfs scripts in azurehpc/scripts. If these scripts are not working then they need to be modified not create new scripts in cc_glusterfs/scripts.

**Comment by garvct** [comment]
Please restore the branch until this is corrected.

**Comment by chadnar2** [comment]
We'll have to dig into whether examples/glusterfs_ephemeral and examples/glusterfs_data_disks use the existing glusterfs_pool.sh. If so, something needs to change. I had to keep the head glusterfs node up for cyclecloud and this was the approach taken for other cyclecloud builds. The glusterfs_pool.sh did not seem to function as designed, so it was broken into 2 scripts (one for master, one for clients). We should talk about the approach then.

**Pull request merged**
