### PR TITLE
Added in managed disks for Lustre for examples/manageddisk_lustre

### PR DESCRIPTION
**Pull request by chadnar2**

### CODE REVIEW

**Comment by garvct** [comment]
This pull request seems to be for azhpc-scp not related to Lustre managed disks?
With the above azhpc-scp change, can you now consistently azhpc-scp using your home isp?

**Comment by chadnar2** [comment]
I haven't tried yet. I didn't make that change so it must have come from Paul. Please give it a try.

**Comment by chadnar2** [comment]
Updated narjitSept2519 to reflect the addition of Lustre Managed Disks

**Comment by edwardsp** [comment]
You have added all the temporary files (including private keys).  I think you probably only want to add the config file and readme?

**Comment by xpillons** [comment]
@edwardsp you may reject that PR as it would be easier to start from a clean one

**Comment by edwardsp** [comment]
Closing PR.  Please create new branch/PR with just the example.

**Comment by chadnar2** [comment]
Moving to delete branch

**Pull request closed without merging**
