### PR TITLE
Create run_benchmark20m-2x120cores.pbs

### PR DESCRIPTION
**Pull request by chadnar2**
This is for openFoam on HBv2

### CODE REVIEW

**Comment by xpillons** [comment]
and finally i think it's not needed as there is already a generic run_benchmark.sh script so even better, you can delete both .pbs files

**Comment by chadnar2** [comment]
This was for HBv2 with 120 cores per node. I can take a look later today at the differences as this file is old.

**Comment by chadnar2** [comment]
So just delete this branch?

**Comment by xpillons** [comment]
yes

**Pull request closed without merging**
