### PR TITLE
Add peering gateway opts

### PR DESCRIPTION
**Pull request by yosoyjay**
Expose additional peering configuration options to eliminate need to manually configure peering with existing vnets.
    
    - Add config dictionary in ['vnet']['peer'] for gateway options
    - Add config fields in ['vnet']['peer'][<peer-name>] for traffic options
    - Add method to delete peerings with azhpc-destroy when defined in config.json
    - Default configs remain unchanged
    - Update to README.md to reflect changes with example of adding peering

### CODE REVIEW

**Review by xpillons — APPROVED** [review]
sounds good to me, however i'm not able to test it

**Comment by yosoyjay** [comment]
Good point that I meant to bring up with the PR, is there a preferred way to add tests?

**Comment by xpillons** [comment]
> Good point that I meant to bring up with the PR, is there a preferred way to add tests?

Not really. We trust your tests

**Comment by yosoyjay** [comment]
Okay, I'll add some testing.

**Comment by yosoyjay** [comment]
How are tests run?  I see the `ci` dir, various bash scripts, what looks like CI yaml config files, but I'm not sure at all how this is actually run.

**Comment by yosoyjay** [comment]
@xpillons I tested in a couple of different VPNs and it works as I expect.  However, an interesting side effect is that if you create a new VNet and create a peering to the another VNet that contains a VPN gateway with an active VPN connection, it drops the connection. You can immediately reconnect, but it is not ideal.  Do you have any idea about how to eliminate behavior?

**Comment by xpillons** [comment]
I've seen this too and I don't know how to fix that. It's good to merge for me now.

**Comment by yosoyjay** [comment]
Okay, thanks for confirming the behavior is not just limited to that.  I don't have permissions to merge, so you'll have to do that.

**Pull request merged**
